FIRRTL version 1.1.0
circuit BufferAccumulator :
  module BufferAccumulator :
    input clock : Clock
    input reset : UInt<1>
    input io_adcValues_0 : UInt<8>
    input io_adcValues_1 : UInt<8>
    input io_adcValues_2 : UInt<8>
    input io_adcValues_3 : UInt<8>
    input io_adcValues_4 : UInt<8>
    input io_adcValues_5 : UInt<8>
    input io_adcValues_6 : UInt<8>
    input io_adcValues_7 : UInt<8>
    input io_adcValues_8 : UInt<8>
    input io_adcValues_9 : UInt<8>
    input io_adcValues_10 : UInt<8>
    input io_adcValues_11 : UInt<8>
    input io_adcValues_12 : UInt<8>
    input io_adcValues_13 : UInt<8>
    input io_adcValues_14 : UInt<8>
    input io_adcValues_15 : UInt<8>
    input io_adcValues_16 : UInt<8>
    input io_adcValues_17 : UInt<8>
    input io_adcValues_18 : UInt<8>
    input io_adcValues_19 : UInt<8>
    input io_adcValues_20 : UInt<8>
    input io_adcValues_21 : UInt<8>
    input io_adcValues_22 : UInt<8>
    input io_adcValues_23 : UInt<8>
    input io_adcValues_24 : UInt<8>
    input io_adcValues_25 : UInt<8>
    input io_adcValues_26 : UInt<8>
    input io_adcValues_27 : UInt<8>
    input io_adcValues_28 : UInt<8>
    input io_adcValues_29 : UInt<8>
    input io_adcValues_30 : UInt<8>
    input io_adcValues_31 : UInt<8>
    input io_adcValues_32 : UInt<8>
    input io_adcValues_33 : UInt<8>
    input io_adcValues_34 : UInt<8>
    input io_adcValues_35 : UInt<8>
    input io_adcValues_36 : UInt<8>
    input io_adcValues_37 : UInt<8>
    input io_adcValues_38 : UInt<8>
    input io_adcValues_39 : UInt<8>
    input io_adcValues_40 : UInt<8>
    input io_adcValues_41 : UInt<8>
    input io_adcValues_42 : UInt<8>
    input io_adcValues_43 : UInt<8>
    input io_adcValues_44 : UInt<8>
    input io_adcValues_45 : UInt<8>
    input io_adcValues_46 : UInt<8>
    input io_adcValues_47 : UInt<8>
    input io_adcValues_48 : UInt<8>
    input io_adcValues_49 : UInt<8>
    input io_adcValues_50 : UInt<8>
    input io_adcValues_51 : UInt<8>
    input io_adcValues_52 : UInt<8>
    input io_adcValues_53 : UInt<8>
    input io_adcValues_54 : UInt<8>
    input io_adcValues_55 : UInt<8>
    input io_adcValues_56 : UInt<8>
    input io_adcValues_57 : UInt<8>
    input io_adcValues_58 : UInt<8>
    input io_adcValues_59 : UInt<8>
    input io_adcValues_60 : UInt<8>
    input io_adcValues_61 : UInt<8>
    input io_adcValues_62 : UInt<8>
    input io_adcValues_63 : UInt<8>
    input io_adcValues_64 : UInt<8>
    input io_adcValues_65 : UInt<8>
    input io_adcValues_66 : UInt<8>
    input io_adcValues_67 : UInt<8>
    input io_adcValues_68 : UInt<8>
    input io_adcValues_69 : UInt<8>
    input io_adcValues_70 : UInt<8>
    input io_adcValues_71 : UInt<8>
    input io_adcValues_72 : UInt<8>
    input io_adcValues_73 : UInt<8>
    input io_adcValues_74 : UInt<8>
    input io_adcValues_75 : UInt<8>
    input io_adcValues_76 : UInt<8>
    input io_adcValues_77 : UInt<8>
    input io_adcValues_78 : UInt<8>
    input io_adcValues_79 : UInt<8>
    input io_adcValues_80 : UInt<8>
    input io_adcValues_81 : UInt<8>
    input io_adcValues_82 : UInt<8>
    input io_adcValues_83 : UInt<8>
    input io_adcValues_84 : UInt<8>
    input io_adcValues_85 : UInt<8>
    input io_adcValues_86 : UInt<8>
    input io_adcValues_87 : UInt<8>
    input io_adcValues_88 : UInt<8>
    input io_adcValues_89 : UInt<8>
    input io_adcValues_90 : UInt<8>
    input io_adcValues_91 : UInt<8>
    input io_adcValues_92 : UInt<8>
    input io_adcValues_93 : UInt<8>
    input io_adcValues_94 : UInt<8>
    input io_adcValues_95 : UInt<8>
    input io_adcValues_96 : UInt<8>
    input io_adcValues_97 : UInt<8>
    input io_adcValues_98 : UInt<8>
    input io_adcValues_99 : UInt<8>
    input io_adcValues_100 : UInt<8>
    input io_adcValues_101 : UInt<8>
    input io_adcValues_102 : UInt<8>
    input io_adcValues_103 : UInt<8>
    input io_adcValues_104 : UInt<8>
    input io_adcValues_105 : UInt<8>
    input io_adcValues_106 : UInt<8>
    input io_adcValues_107 : UInt<8>
    input io_adcValues_108 : UInt<8>
    input io_adcValues_109 : UInt<8>
    input io_adcValues_110 : UInt<8>
    input io_adcValues_111 : UInt<8>
    input io_adcValues_112 : UInt<8>
    input io_adcValues_113 : UInt<8>
    input io_adcValues_114 : UInt<8>
    input io_adcValues_115 : UInt<8>
    input io_adcValues_116 : UInt<8>
    input io_adcValues_117 : UInt<8>
    input io_adcValues_118 : UInt<8>
    input io_adcValues_119 : UInt<8>
    input io_adcValues_120 : UInt<8>
    input io_adcValues_121 : UInt<8>
    input io_adcValues_122 : UInt<8>
    input io_adcValues_123 : UInt<8>
    input io_adcValues_124 : UInt<8>
    input io_adcValues_125 : UInt<8>
    input io_adcValues_126 : UInt<8>
    input io_adcValues_127 : UInt<8>
    output io_zeroSums_0 : UInt<8>
    output io_zeroSums_1 : UInt<8>
    output io_zeroSums_2 : UInt<8>
    output io_zeroSums_3 : UInt<8>
    output io_zeroSums_4 : UInt<8>
    output io_zeroSums_5 : UInt<8>
    output io_zeroSums_6 : UInt<8>
    output io_zeroSums_7 : UInt<8>

    reg zeroAccumulators_0 : UInt<8>, clock with :
      reset => (UInt<1>("h0"), zeroAccumulators_0) @[BufferAccumulator.scala 12:33]
    reg zeroAccumulators_1 : UInt<8>, clock with :
      reset => (UInt<1>("h0"), zeroAccumulators_1) @[BufferAccumulator.scala 12:33]
    reg zeroAccumulators_2 : UInt<8>, clock with :
      reset => (UInt<1>("h0"), zeroAccumulators_2) @[BufferAccumulator.scala 12:33]
    reg zeroAccumulators_3 : UInt<8>, clock with :
      reset => (UInt<1>("h0"), zeroAccumulators_3) @[BufferAccumulator.scala 12:33]
    reg zeroAccumulators_4 : UInt<8>, clock with :
      reset => (UInt<1>("h0"), zeroAccumulators_4) @[BufferAccumulator.scala 12:33]
    reg zeroAccumulators_5 : UInt<8>, clock with :
      reset => (UInt<1>("h0"), zeroAccumulators_5) @[BufferAccumulator.scala 12:33]
    reg zeroAccumulators_6 : UInt<8>, clock with :
      reset => (UInt<1>("h0"), zeroAccumulators_6) @[BufferAccumulator.scala 12:33]
    reg zeroAccumulators_7 : UInt<8>, clock with :
      reset => (UInt<1>("h0"), zeroAccumulators_7) @[BufferAccumulator.scala 12:33]
    reg lineCounter : UInt<4>, clock with :
      reset => (UInt<1>("h0"), lineCounter) @[BufferAccumulator.scala 14:28]
    node _T = eq(lineCounter, UInt<4>("hf")) @[BufferAccumulator.scala 16:21]
    node _lineCounter_T = add(lineCounter, UInt<1>("h1")) @[BufferAccumulator.scala 20:32]
    node _lineCounter_T_1 = tail(_lineCounter_T, 1) @[BufferAccumulator.scala 20:32]
    node _zeroCount_T = eq(io_adcValues_0, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_1 = eq(io_adcValues_1, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_2 = eq(io_adcValues_2, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_3 = eq(io_adcValues_3, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_4 = eq(io_adcValues_4, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_5 = eq(io_adcValues_5, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_6 = eq(io_adcValues_6, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_7 = eq(io_adcValues_7, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_8 = eq(io_adcValues_8, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_9 = eq(io_adcValues_9, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_10 = eq(io_adcValues_10, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_11 = eq(io_adcValues_11, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_12 = eq(io_adcValues_12, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_13 = eq(io_adcValues_13, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_14 = eq(io_adcValues_14, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_15 = eq(io_adcValues_15, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_16 = add(UInt<1>("h0"), _zeroCount_T) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_17 = add(_zeroCount_T_16, _zeroCount_T_1) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_18 = add(_zeroCount_T_17, _zeroCount_T_2) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_19 = add(_zeroCount_T_18, _zeroCount_T_3) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_20 = add(_zeroCount_T_19, _zeroCount_T_4) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_21 = add(_zeroCount_T_20, _zeroCount_T_5) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_22 = add(_zeroCount_T_21, _zeroCount_T_6) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_23 = add(_zeroCount_T_22, _zeroCount_T_7) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_24 = add(_zeroCount_T_23, _zeroCount_T_8) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_25 = add(_zeroCount_T_24, _zeroCount_T_9) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_26 = add(_zeroCount_T_25, _zeroCount_T_10) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_27 = add(_zeroCount_T_26, _zeroCount_T_11) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_28 = add(_zeroCount_T_27, _zeroCount_T_12) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_29 = add(_zeroCount_T_28, _zeroCount_T_13) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_30 = add(_zeroCount_T_29, _zeroCount_T_14) @[BufferAccumulator.scala 24:70]
    node zeroCount = add(_zeroCount_T_30, _zeroCount_T_15) @[BufferAccumulator.scala 24:70]
    node _zeroAccumulators_0_T = add(zeroAccumulators_0, zeroCount) @[BufferAccumulator.scala 26:50]
    node _zeroAccumulators_0_T_1 = tail(_zeroAccumulators_0_T, 1) @[BufferAccumulator.scala 26:50]
    node _zeroCount_T_31 = eq(io_adcValues_16, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_32 = eq(io_adcValues_17, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_33 = eq(io_adcValues_18, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_34 = eq(io_adcValues_19, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_35 = eq(io_adcValues_20, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_36 = eq(io_adcValues_21, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_37 = eq(io_adcValues_22, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_38 = eq(io_adcValues_23, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_39 = eq(io_adcValues_24, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_40 = eq(io_adcValues_25, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_41 = eq(io_adcValues_26, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_42 = eq(io_adcValues_27, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_43 = eq(io_adcValues_28, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_44 = eq(io_adcValues_29, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_45 = eq(io_adcValues_30, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_46 = eq(io_adcValues_31, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_47 = add(UInt<1>("h0"), _zeroCount_T_31) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_48 = add(_zeroCount_T_47, _zeroCount_T_32) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_49 = add(_zeroCount_T_48, _zeroCount_T_33) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_50 = add(_zeroCount_T_49, _zeroCount_T_34) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_51 = add(_zeroCount_T_50, _zeroCount_T_35) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_52 = add(_zeroCount_T_51, _zeroCount_T_36) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_53 = add(_zeroCount_T_52, _zeroCount_T_37) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_54 = add(_zeroCount_T_53, _zeroCount_T_38) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_55 = add(_zeroCount_T_54, _zeroCount_T_39) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_56 = add(_zeroCount_T_55, _zeroCount_T_40) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_57 = add(_zeroCount_T_56, _zeroCount_T_41) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_58 = add(_zeroCount_T_57, _zeroCount_T_42) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_59 = add(_zeroCount_T_58, _zeroCount_T_43) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_60 = add(_zeroCount_T_59, _zeroCount_T_44) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_61 = add(_zeroCount_T_60, _zeroCount_T_45) @[BufferAccumulator.scala 24:70]
    node zeroCount_1 = add(_zeroCount_T_61, _zeroCount_T_46) @[BufferAccumulator.scala 24:70]
    node _zeroAccumulators_1_T = add(zeroAccumulators_1, zeroCount_1) @[BufferAccumulator.scala 26:50]
    node _zeroAccumulators_1_T_1 = tail(_zeroAccumulators_1_T, 1) @[BufferAccumulator.scala 26:50]
    node _zeroCount_T_62 = eq(io_adcValues_32, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_63 = eq(io_adcValues_33, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_64 = eq(io_adcValues_34, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_65 = eq(io_adcValues_35, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_66 = eq(io_adcValues_36, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_67 = eq(io_adcValues_37, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_68 = eq(io_adcValues_38, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_69 = eq(io_adcValues_39, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_70 = eq(io_adcValues_40, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_71 = eq(io_adcValues_41, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_72 = eq(io_adcValues_42, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_73 = eq(io_adcValues_43, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_74 = eq(io_adcValues_44, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_75 = eq(io_adcValues_45, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_76 = eq(io_adcValues_46, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_77 = eq(io_adcValues_47, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_78 = add(UInt<1>("h0"), _zeroCount_T_62) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_79 = add(_zeroCount_T_78, _zeroCount_T_63) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_80 = add(_zeroCount_T_79, _zeroCount_T_64) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_81 = add(_zeroCount_T_80, _zeroCount_T_65) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_82 = add(_zeroCount_T_81, _zeroCount_T_66) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_83 = add(_zeroCount_T_82, _zeroCount_T_67) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_84 = add(_zeroCount_T_83, _zeroCount_T_68) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_85 = add(_zeroCount_T_84, _zeroCount_T_69) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_86 = add(_zeroCount_T_85, _zeroCount_T_70) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_87 = add(_zeroCount_T_86, _zeroCount_T_71) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_88 = add(_zeroCount_T_87, _zeroCount_T_72) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_89 = add(_zeroCount_T_88, _zeroCount_T_73) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_90 = add(_zeroCount_T_89, _zeroCount_T_74) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_91 = add(_zeroCount_T_90, _zeroCount_T_75) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_92 = add(_zeroCount_T_91, _zeroCount_T_76) @[BufferAccumulator.scala 24:70]
    node zeroCount_2 = add(_zeroCount_T_92, _zeroCount_T_77) @[BufferAccumulator.scala 24:70]
    node _zeroAccumulators_2_T = add(zeroAccumulators_2, zeroCount_2) @[BufferAccumulator.scala 26:50]
    node _zeroAccumulators_2_T_1 = tail(_zeroAccumulators_2_T, 1) @[BufferAccumulator.scala 26:50]
    node _zeroCount_T_93 = eq(io_adcValues_48, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_94 = eq(io_adcValues_49, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_95 = eq(io_adcValues_50, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_96 = eq(io_adcValues_51, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_97 = eq(io_adcValues_52, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_98 = eq(io_adcValues_53, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_99 = eq(io_adcValues_54, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_100 = eq(io_adcValues_55, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_101 = eq(io_adcValues_56, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_102 = eq(io_adcValues_57, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_103 = eq(io_adcValues_58, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_104 = eq(io_adcValues_59, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_105 = eq(io_adcValues_60, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_106 = eq(io_adcValues_61, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_107 = eq(io_adcValues_62, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_108 = eq(io_adcValues_63, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_109 = add(UInt<1>("h0"), _zeroCount_T_93) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_110 = add(_zeroCount_T_109, _zeroCount_T_94) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_111 = add(_zeroCount_T_110, _zeroCount_T_95) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_112 = add(_zeroCount_T_111, _zeroCount_T_96) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_113 = add(_zeroCount_T_112, _zeroCount_T_97) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_114 = add(_zeroCount_T_113, _zeroCount_T_98) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_115 = add(_zeroCount_T_114, _zeroCount_T_99) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_116 = add(_zeroCount_T_115, _zeroCount_T_100) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_117 = add(_zeroCount_T_116, _zeroCount_T_101) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_118 = add(_zeroCount_T_117, _zeroCount_T_102) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_119 = add(_zeroCount_T_118, _zeroCount_T_103) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_120 = add(_zeroCount_T_119, _zeroCount_T_104) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_121 = add(_zeroCount_T_120, _zeroCount_T_105) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_122 = add(_zeroCount_T_121, _zeroCount_T_106) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_123 = add(_zeroCount_T_122, _zeroCount_T_107) @[BufferAccumulator.scala 24:70]
    node zeroCount_3 = add(_zeroCount_T_123, _zeroCount_T_108) @[BufferAccumulator.scala 24:70]
    node _zeroAccumulators_3_T = add(zeroAccumulators_3, zeroCount_3) @[BufferAccumulator.scala 26:50]
    node _zeroAccumulators_3_T_1 = tail(_zeroAccumulators_3_T, 1) @[BufferAccumulator.scala 26:50]
    node _zeroCount_T_124 = eq(io_adcValues_64, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_125 = eq(io_adcValues_65, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_126 = eq(io_adcValues_66, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_127 = eq(io_adcValues_67, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_128 = eq(io_adcValues_68, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_129 = eq(io_adcValues_69, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_130 = eq(io_adcValues_70, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_131 = eq(io_adcValues_71, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_132 = eq(io_adcValues_72, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_133 = eq(io_adcValues_73, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_134 = eq(io_adcValues_74, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_135 = eq(io_adcValues_75, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_136 = eq(io_adcValues_76, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_137 = eq(io_adcValues_77, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_138 = eq(io_adcValues_78, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_139 = eq(io_adcValues_79, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_140 = add(UInt<1>("h0"), _zeroCount_T_124) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_141 = add(_zeroCount_T_140, _zeroCount_T_125) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_142 = add(_zeroCount_T_141, _zeroCount_T_126) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_143 = add(_zeroCount_T_142, _zeroCount_T_127) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_144 = add(_zeroCount_T_143, _zeroCount_T_128) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_145 = add(_zeroCount_T_144, _zeroCount_T_129) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_146 = add(_zeroCount_T_145, _zeroCount_T_130) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_147 = add(_zeroCount_T_146, _zeroCount_T_131) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_148 = add(_zeroCount_T_147, _zeroCount_T_132) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_149 = add(_zeroCount_T_148, _zeroCount_T_133) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_150 = add(_zeroCount_T_149, _zeroCount_T_134) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_151 = add(_zeroCount_T_150, _zeroCount_T_135) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_152 = add(_zeroCount_T_151, _zeroCount_T_136) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_153 = add(_zeroCount_T_152, _zeroCount_T_137) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_154 = add(_zeroCount_T_153, _zeroCount_T_138) @[BufferAccumulator.scala 24:70]
    node zeroCount_4 = add(_zeroCount_T_154, _zeroCount_T_139) @[BufferAccumulator.scala 24:70]
    node _zeroAccumulators_4_T = add(zeroAccumulators_4, zeroCount_4) @[BufferAccumulator.scala 26:50]
    node _zeroAccumulators_4_T_1 = tail(_zeroAccumulators_4_T, 1) @[BufferAccumulator.scala 26:50]
    node _zeroCount_T_155 = eq(io_adcValues_80, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_156 = eq(io_adcValues_81, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_157 = eq(io_adcValues_82, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_158 = eq(io_adcValues_83, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_159 = eq(io_adcValues_84, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_160 = eq(io_adcValues_85, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_161 = eq(io_adcValues_86, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_162 = eq(io_adcValues_87, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_163 = eq(io_adcValues_88, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_164 = eq(io_adcValues_89, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_165 = eq(io_adcValues_90, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_166 = eq(io_adcValues_91, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_167 = eq(io_adcValues_92, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_168 = eq(io_adcValues_93, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_169 = eq(io_adcValues_94, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_170 = eq(io_adcValues_95, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_171 = add(UInt<1>("h0"), _zeroCount_T_155) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_172 = add(_zeroCount_T_171, _zeroCount_T_156) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_173 = add(_zeroCount_T_172, _zeroCount_T_157) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_174 = add(_zeroCount_T_173, _zeroCount_T_158) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_175 = add(_zeroCount_T_174, _zeroCount_T_159) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_176 = add(_zeroCount_T_175, _zeroCount_T_160) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_177 = add(_zeroCount_T_176, _zeroCount_T_161) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_178 = add(_zeroCount_T_177, _zeroCount_T_162) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_179 = add(_zeroCount_T_178, _zeroCount_T_163) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_180 = add(_zeroCount_T_179, _zeroCount_T_164) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_181 = add(_zeroCount_T_180, _zeroCount_T_165) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_182 = add(_zeroCount_T_181, _zeroCount_T_166) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_183 = add(_zeroCount_T_182, _zeroCount_T_167) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_184 = add(_zeroCount_T_183, _zeroCount_T_168) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_185 = add(_zeroCount_T_184, _zeroCount_T_169) @[BufferAccumulator.scala 24:70]
    node zeroCount_5 = add(_zeroCount_T_185, _zeroCount_T_170) @[BufferAccumulator.scala 24:70]
    node _zeroAccumulators_5_T = add(zeroAccumulators_5, zeroCount_5) @[BufferAccumulator.scala 26:50]
    node _zeroAccumulators_5_T_1 = tail(_zeroAccumulators_5_T, 1) @[BufferAccumulator.scala 26:50]
    node _zeroCount_T_186 = eq(io_adcValues_96, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_187 = eq(io_adcValues_97, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_188 = eq(io_adcValues_98, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_189 = eq(io_adcValues_99, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_190 = eq(io_adcValues_100, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_191 = eq(io_adcValues_101, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_192 = eq(io_adcValues_102, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_193 = eq(io_adcValues_103, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_194 = eq(io_adcValues_104, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_195 = eq(io_adcValues_105, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_196 = eq(io_adcValues_106, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_197 = eq(io_adcValues_107, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_198 = eq(io_adcValues_108, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_199 = eq(io_adcValues_109, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_200 = eq(io_adcValues_110, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_201 = eq(io_adcValues_111, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_202 = add(UInt<1>("h0"), _zeroCount_T_186) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_203 = add(_zeroCount_T_202, _zeroCount_T_187) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_204 = add(_zeroCount_T_203, _zeroCount_T_188) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_205 = add(_zeroCount_T_204, _zeroCount_T_189) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_206 = add(_zeroCount_T_205, _zeroCount_T_190) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_207 = add(_zeroCount_T_206, _zeroCount_T_191) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_208 = add(_zeroCount_T_207, _zeroCount_T_192) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_209 = add(_zeroCount_T_208, _zeroCount_T_193) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_210 = add(_zeroCount_T_209, _zeroCount_T_194) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_211 = add(_zeroCount_T_210, _zeroCount_T_195) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_212 = add(_zeroCount_T_211, _zeroCount_T_196) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_213 = add(_zeroCount_T_212, _zeroCount_T_197) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_214 = add(_zeroCount_T_213, _zeroCount_T_198) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_215 = add(_zeroCount_T_214, _zeroCount_T_199) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_216 = add(_zeroCount_T_215, _zeroCount_T_200) @[BufferAccumulator.scala 24:70]
    node zeroCount_6 = add(_zeroCount_T_216, _zeroCount_T_201) @[BufferAccumulator.scala 24:70]
    node _zeroAccumulators_6_T = add(zeroAccumulators_6, zeroCount_6) @[BufferAccumulator.scala 26:50]
    node _zeroAccumulators_6_T_1 = tail(_zeroAccumulators_6_T, 1) @[BufferAccumulator.scala 26:50]
    node _zeroCount_T_217 = eq(io_adcValues_112, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_218 = eq(io_adcValues_113, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_219 = eq(io_adcValues_114, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_220 = eq(io_adcValues_115, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_221 = eq(io_adcValues_116, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_222 = eq(io_adcValues_117, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_223 = eq(io_adcValues_118, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_224 = eq(io_adcValues_119, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_225 = eq(io_adcValues_120, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_226 = eq(io_adcValues_121, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_227 = eq(io_adcValues_122, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_228 = eq(io_adcValues_123, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_229 = eq(io_adcValues_124, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_230 = eq(io_adcValues_125, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_231 = eq(io_adcValues_126, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_232 = eq(io_adcValues_127, UInt<1>("h0")) @[BufferAccumulator.scala 24:41]
    node _zeroCount_T_233 = add(UInt<1>("h0"), _zeroCount_T_217) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_234 = add(_zeroCount_T_233, _zeroCount_T_218) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_235 = add(_zeroCount_T_234, _zeroCount_T_219) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_236 = add(_zeroCount_T_235, _zeroCount_T_220) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_237 = add(_zeroCount_T_236, _zeroCount_T_221) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_238 = add(_zeroCount_T_237, _zeroCount_T_222) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_239 = add(_zeroCount_T_238, _zeroCount_T_223) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_240 = add(_zeroCount_T_239, _zeroCount_T_224) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_241 = add(_zeroCount_T_240, _zeroCount_T_225) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_242 = add(_zeroCount_T_241, _zeroCount_T_226) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_243 = add(_zeroCount_T_242, _zeroCount_T_227) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_244 = add(_zeroCount_T_243, _zeroCount_T_228) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_245 = add(_zeroCount_T_244, _zeroCount_T_229) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_246 = add(_zeroCount_T_245, _zeroCount_T_230) @[BufferAccumulator.scala 24:70]
    node _zeroCount_T_247 = add(_zeroCount_T_246, _zeroCount_T_231) @[BufferAccumulator.scala 24:70]
    node zeroCount_7 = add(_zeroCount_T_247, _zeroCount_T_232) @[BufferAccumulator.scala 24:70]
    node _zeroAccumulators_7_T = add(zeroAccumulators_7, zeroCount_7) @[BufferAccumulator.scala 26:50]
    node _zeroAccumulators_7_T_1 = tail(_zeroAccumulators_7_T, 1) @[BufferAccumulator.scala 26:50]
    node _GEN_0 = mux(_T, UInt<1>("h0"), _lineCounter_T_1) @[BufferAccumulator.scala 16:30 17:17 20:17]
    node _WIRE_0 = UInt<8>("h0") @[BufferAccumulator.scala 18:{32,32}]
    node _GEN_1 = mux(_T, _WIRE_0, _zeroAccumulators_0_T_1) @[BufferAccumulator.scala 16:30 18:22 26:27]
    node _WIRE_1 = UInt<8>("h0") @[BufferAccumulator.scala 18:{32,32}]
    node _GEN_2 = mux(_T, _WIRE_1, _zeroAccumulators_1_T_1) @[BufferAccumulator.scala 16:30 18:22 26:27]
    node _WIRE_2 = UInt<8>("h0") @[BufferAccumulator.scala 18:{32,32}]
    node _GEN_3 = mux(_T, _WIRE_2, _zeroAccumulators_2_T_1) @[BufferAccumulator.scala 16:30 18:22 26:27]
    node _WIRE_3 = UInt<8>("h0") @[BufferAccumulator.scala 18:{32,32}]
    node _GEN_4 = mux(_T, _WIRE_3, _zeroAccumulators_3_T_1) @[BufferAccumulator.scala 16:30 18:22 26:27]
    node _WIRE_4 = UInt<8>("h0") @[BufferAccumulator.scala 18:{32,32}]
    node _GEN_5 = mux(_T, _WIRE_4, _zeroAccumulators_4_T_1) @[BufferAccumulator.scala 16:30 18:22 26:27]
    node _WIRE_5 = UInt<8>("h0") @[BufferAccumulator.scala 18:{32,32}]
    node _GEN_6 = mux(_T, _WIRE_5, _zeroAccumulators_5_T_1) @[BufferAccumulator.scala 16:30 18:22 26:27]
    node _WIRE_6 = UInt<8>("h0") @[BufferAccumulator.scala 18:{32,32}]
    node _GEN_7 = mux(_T, _WIRE_6, _zeroAccumulators_6_T_1) @[BufferAccumulator.scala 16:30 18:22 26:27]
    node _WIRE_7 = UInt<8>("h0") @[BufferAccumulator.scala 18:{32,32}]
    node _GEN_8 = mux(_T, _WIRE_7, _zeroAccumulators_7_T_1) @[BufferAccumulator.scala 16:30 18:22 26:27]
    node _zeroAccumulators_WIRE_0 = UInt<8>("h0") @[BufferAccumulator.scala 12:{41,41}]
    node _zeroAccumulators_WIRE_1 = UInt<8>("h0") @[BufferAccumulator.scala 12:{41,41}]
    node _zeroAccumulators_WIRE_2 = UInt<8>("h0") @[BufferAccumulator.scala 12:{41,41}]
    node _zeroAccumulators_WIRE_3 = UInt<8>("h0") @[BufferAccumulator.scala 12:{41,41}]
    node _zeroAccumulators_WIRE_4 = UInt<8>("h0") @[BufferAccumulator.scala 12:{41,41}]
    node _zeroAccumulators_WIRE_5 = UInt<8>("h0") @[BufferAccumulator.scala 12:{41,41}]
    node _zeroAccumulators_WIRE_6 = UInt<8>("h0") @[BufferAccumulator.scala 12:{41,41}]
    node _zeroAccumulators_WIRE_7 = UInt<8>("h0") @[BufferAccumulator.scala 12:{41,41}]
    io_zeroSums_0 <= zeroAccumulators_0 @[BufferAccumulator.scala 30:15]
    io_zeroSums_1 <= zeroAccumulators_1 @[BufferAccumulator.scala 30:15]
    io_zeroSums_2 <= zeroAccumulators_2 @[BufferAccumulator.scala 30:15]
    io_zeroSums_3 <= zeroAccumulators_3 @[BufferAccumulator.scala 30:15]
    io_zeroSums_4 <= zeroAccumulators_4 @[BufferAccumulator.scala 30:15]
    io_zeroSums_5 <= zeroAccumulators_5 @[BufferAccumulator.scala 30:15]
    io_zeroSums_6 <= zeroAccumulators_6 @[BufferAccumulator.scala 30:15]
    io_zeroSums_7 <= zeroAccumulators_7 @[BufferAccumulator.scala 30:15]
    zeroAccumulators_0 <= bits(mux(reset, _zeroAccumulators_WIRE_0, _GEN_1), 7, 0) @[BufferAccumulator.scala 12:{33,33}]
    zeroAccumulators_1 <= bits(mux(reset, _zeroAccumulators_WIRE_1, _GEN_2), 7, 0) @[BufferAccumulator.scala 12:{33,33}]
    zeroAccumulators_2 <= bits(mux(reset, _zeroAccumulators_WIRE_2, _GEN_3), 7, 0) @[BufferAccumulator.scala 12:{33,33}]
    zeroAccumulators_3 <= bits(mux(reset, _zeroAccumulators_WIRE_3, _GEN_4), 7, 0) @[BufferAccumulator.scala 12:{33,33}]
    zeroAccumulators_4 <= bits(mux(reset, _zeroAccumulators_WIRE_4, _GEN_5), 7, 0) @[BufferAccumulator.scala 12:{33,33}]
    zeroAccumulators_5 <= bits(mux(reset, _zeroAccumulators_WIRE_5, _GEN_6), 7, 0) @[BufferAccumulator.scala 12:{33,33}]
    zeroAccumulators_6 <= bits(mux(reset, _zeroAccumulators_WIRE_6, _GEN_7), 7, 0) @[BufferAccumulator.scala 12:{33,33}]
    zeroAccumulators_7 <= bits(mux(reset, _zeroAccumulators_WIRE_7, _GEN_8), 7, 0) @[BufferAccumulator.scala 12:{33,33}]
    lineCounter <= mux(reset, UInt<4>("h0"), _GEN_0) @[BufferAccumulator.scala 14:{28,28}]
